version: "3.9"
services:
  controller:
    image: paravirtualtishu/controller:latest
    pull_policy: always
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DOCKER_API_VERSION=1.41
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    command: |
      redis-server
        --save 60 1
        --loglevel warning
