version: "3.9"
services:
  controller:
    image: paravirtualtishu/controller:latest
    pull_policy: always
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DOCKER_API_VERSION=1.41
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    command: |
      redis-server
        --save 60 1
        --loglevel warning
  postgres:
    image: paravirtualtishu/postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=big-data-ci
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: '{"api_addr": "http://0.0.0.0:8200", "storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
    command: server

volumes:
  postgres_data:
  vault_data:
