image: "paravirtualtishu/base"
stages:
  build:
    script: |
      echo "Output from build"
      which gcc
      git clone https://github.com/blackbird71SR/Hello-World.git
      cd Hello-World
      gcc HelloWorld.c -o HelloWorld.out
      ./HelloWorld.out
    artifacts:
      - HelloWorld.out
  test1:
    script: |
      echo test1
      which javac
    depends_on:
      - stage: build
        artifacts: false
  test2:
    script: |
      echo test2
      ls -lart HelloWorld.out
      ./HelloWorld.out
    depends_on:
      - stage: build
        artifacts: true
      - stage: test1
